language: rust
dist: trusty

rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly

sudo: false
addons:
  apt:
    packages:
    - libleveldb-dev

env:
- LEVELDB_LIB_DIR=/usr/lib/x86_64-linux-gnu