[package]
name = "leveldb-sys"
version = "3.0.0"
authors = ["Andrew Dunham <andrew@du.nham.ca>", "Florian Gilcher <florian.gilcher@asquera.de>"]

description = "FFI bindings to LevelDB"
repository = "https://github.com/andrew-d/leveldb-rs"
license = "MIT"

build = "src/build.rs"
links = "leveldb"

[dependencies]
libc = "0.2"
